server:
   port: 8083
   servlet:
      context-path: /training-demo
   compression:
      enabled: false
spring:
   h2:
     console:
       enabled: true
   servlet:
     multipart:
       max-file-size: 5MB
       max-request-size: 6MB
management:
  endpoints:
    web:
      exposure:
        include: health, beans,loggers
spring-doc:
  show-actuator: true